db:
  image: mariadb
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: password
  ports:
    - 3306:3306
  volumes:
    - ./db/data:/var/lib/mysql
    - ./db/conf:/etc/mysql/

adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080

api:
  build: .
  restart: on-failure
  ports:
   - "5000:5000"
  volumes:
   - ./app:/app
